### PR TITLE
i#2478: Fix Compilation error on linux mint 21.1 

### LINKED ISSUE #2478: Compilation error on linux mint 21.1
**Describe the bug**
Trying to buid Dr Memory from scratch on linux mint vera (gcc version 11.0.3).

**To Reproduce**

1. mkdir build.
2. cd build.
3. cmake ...
4. make

**Screenshots or Pasted Text**
<pre>
```
[ 18%] Building C object drsyscall/CMakeFiles/drsyscall_static.dir/drsyscall_linux.c.o
/drmemory/drsyscall/drsyscall_linux.c: In function ‘handle_semctl’:
/drmemory/drsyscall/drsyscall_linux.c:981:9: error: ‘arg_val’ is used uninitialized [-Werror=uninitialized]
  981 |     arg = *(union semun *) &arg_val;
      |     ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/drmemory/drsyscall/drsyscall_linux.c:975:15: note: ‘arg_val’ declared here
  975 |     ptr_int_t arg_val;
      |               ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [drsyscall/CMakeFiles/drsyscall_static.dir/build.make:104 : drsyscall/CMakeFiles/drsyscall_static.dir/drsyscall_linux.c.o] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:4620 : drsyscall/CMakeFiles/drsyscall_static.dir/all] Erreur 2
make: *** [Makefile:166 : all] Erreur 2

```
</pre>

**Versions**
- Current git version (pulled today)
- Linux mint vera 21.1 X86_64

### PR DESCRIPTION
**Pull request by Egor-OSSRevival**
The code changes involve updating the handling of the arg variable, which is used in the handle_semctl function to represent the semun union argument passed to the semctl system call. The main change is to dereference a pointer to the arg variable instead of using a direct structure assignment.

Fixes #2478

### CODE REVIEW

File: drsyscall/drsyscall_linux.c [hunk 1]
```diff
@@ -973,12 +973,12 @@ handle_semctl(void *drcontext, cls_syscall_t *pt, sysarg_iter_info_t *ii,
...
     uint cmd;
     ptr_int_t arg_val;
-    union semun arg;
+    union semun *arg_ptr;
     int semid;
     ASSERT(argnum_semid + 3 < SYSCALL_NUM_ARG_STORE, "index too high");
     cmd = (uint) pt->sysarg[argnum_semid + 2];
     arg_val = (ptr_int_t) pt->sysarg[argnum_semid + 3];
-    arg = *(union semun *) &arg_val;
+    arg_ptr = (union semun *)arg_val;
```
Comment (derekbruening) [inline drsyscall/drsyscall_linux.c:981]: This is a reasonable fix for the code that was there.  But the original code looks like it was missing a safe_read before de-referencing this pointer.  That may need to be before each use below so it's after the report_sysargs.  How about for now just adding a comment `XXX: Use safe_read to de-reference below.` here.

File: drsyscall/drsyscall_linux.c [hunk 2]
```diff
@@ -973,12 +973,12 @@ handle_semctl(void *drcontext, cls_syscall_t *pt, sysarg_iter_info_t *ii,
     /* int semctl(int semid, int semnum, int cmd, union semun arg) */
```
Comment (derekbruening) [inline drsyscall/drsyscall_linux.c:973]: > i#2478 Fix Compilation error on linux mint 21.1

style nit: Missing colon after issue number: `i#2478: Fix...`

Comment (derekbruening) [inline drsyscall/drsyscall_linux.c:973]: Please add as the last line of the PR description (becomes the commit message) `Fixes #2478` so the issue will be linked to this PR and so this PR will auto-close the issue.

**Review by derekbruening — APPROVED** [review]

File: drsyscall/drsyscall_linux.c (hunk 2 above)
Comment (Egor-OSSRevival) [reply drsyscall/drsyscall_linux.c:973]: Now not missing

Comment (Egor-OSSRevival) [reply drsyscall/drsyscall_linux.c:973]: Done

File: drsyscall/drsyscall_linux.c (hunk 1 above)
Comment (Egor-OSSRevival) [reply drsyscall/drsyscall_linux.c:981]: Like that?
`    ASSERT(argnum_semid + 3 < SYSCALL_NUM_ARG_STORE, "index too high");
    cmd = (uint) pt->sysarg[argnum_semid + 2];
    arg_val = (ptr_int_t) pt->sysarg[argnum_semid + 3];
    /*XXX: Use safe_read to de-reference below. */
    arg_ptr = (union semun *)arg_val;
    semid = (int) pt->sysarg[argnum_semid];`

Comment (Egor-OSSRevival) [reply drsyscall/drsyscall_linux.c:982]: Done

**Review by derekbruening — APPROVED** [review]
I invited you to become a committer so for future PRs you could use branches in this repo instead of a clone and use the request review mechanism.
