### PR TITLE
i#1928: Fix cppcheck warning about uninitialized variable

### LINKED ISSUE #1928: warning about potentially uninitialized variable in drfuzz_mutator.c
drfuzz\drfuzz_mutator.c line 228 
map_size can be uninitialized

### PR DESCRIPTION
**Pull request by Artem-OSSRevival**
In previous Cppcheck versions (like 2.8 and earlier) there were some warnings about uninitialized variables. This is easily fixed by trivial initialization with zero. In the new versions of Cppcheck these warnings does not arise, because, the init occurs in another place of the code and new Cppcheck versions can handle it.
But the created commit will still be useful for improving the quality of the code.

**Before:**
```
❯ ./cppcheck --version
Cppcheck 2.8
❯ ./cppcheck /Projects/drmemory/drfuzz/drfuzz_mutator.c
Checking /Projects/drmemory/drfuzz/drfuzz_mutator.c ...
/Projects/drmemory/drfuzz/drfuzz_mutator.c:228:32: error: Uninitialized variable: actual_size [uninitvar]
    if (!res || map == NULL || actual_size < map_size) {
                               ^
/Projects/drmemory/drfuzz/drfuzz_mutator.c:220:11: note: Assuming condition is false
    if (f != INVALID_FILE) {
          ^
/Projects/drmemory/drfuzz/drfuzz_mutator.c:228:32: note: Uninitialized variable: actual_size
    if (!res || map == NULL || actual_size < map_size) {
                               ^
/Projects/drmemory/drfuzz/drfuzz_mutator.c:228:46: error: Uninitialized variable: map_size [uninitvar]
    if (!res || map == NULL || actual_size < map_size) {
                                             ^
/Projects/drmemory/drfuzz/drfuzz_mutator.c:220:11: note: Assuming condition is false
    if (f != INVALID_FILE) {
          ^
/Projects/drmemory/drfuzz/drfuzz_mutator.c:228:46: note: Uninitialized variable: map_size
    if (!res || map == NULL || actual_size < map_size) {
                                             ^
Checking /Projects/drmemory/drfuzz/drfuzz_mutator.c: DYNAMIC_INTERFACE;DYNAMIC_INTERFACE;_DRFUZZ_MUTATOR_H_...
Checking /Projects/drmemory/drfuzz/drfuzz_mutator.c: DYNAMIC_INTERFACE;_DRFUZZ_MUTATOR_H_...
Checking /Projects/drmemory/drfuzz/drfuzz_mutator.c: DYNAMIC_INTERFACE;_DRFUZZ_MUTATOR_H_;WINDOWS...
```
Screenshot:
before_#1928

**After:**
```
❯ ./cppcheck /Projects/drmemory/drfuzz/drfuzz_mutator.c
Checking /Projects/drmemory/drfuzz/drfuzz_mutator.c ...
Checking /Projects/drmemory/drfuzz/drfuzz_mutator.c: DYNAMIC_INTERFACE;DYNAMIC_INTERFACE;_DRFUZZ_MUTATOR_H_...
Checking /Projects/drmemory/drfuzz/drfuzz_mutator.c: DYNAMIC_INTERFACE;_DRFUZZ_MUTATOR_H_...
Checking /Projects/drmemory/drfuzz/drfuzz_mutator.c: DYNAMIC_INTERFACE;_DRFUZZ_MUTATOR_H_;WINDOWS...
```
Screenshot:
after_#1928

Fixes #1928

### CODE REVIEW

**Review by derekbruening — APPROVED** [review]
Thank you for the PR.

File: drfuzz/drfuzz_mutator.c [hunk 1]
```diff
@@ -208,8 +208,8 @@ static bool
 drfuzz_parse_dictionary(const char *file, mutator_t *mutator)
```
Comment (derekbruening) [inline drfuzz/drfuzz_mutator.c:208]: Note that the commit message used on the squash-and-merge is the PR description (1st comment in Conversation) where the image is going to look like this:

```
![before_#1928](https://github.com/user-attachments/assets/140173d7-dd8c-4fd7-af12-75777b3dfdbe)
```

Maybe better to paste the lines instead of using screenshots as it's just text, and then it will be readable in the commit message?

**Review by derekbruening — APPROVED** [review]

File: drfuzz/drfuzz_mutator.c (hunk 1 above)
Comment (derekbruening) [inline drfuzz/drfuzz_mutator.c:208]: Also, this fixes #1928, right?  So instead of `Issue: #1928` it should have `Fixed #1928` on a line by itself.

Comment (Artem-OSSRevival) [reply drfuzz/drfuzz_mutator.c:208]: Tried to combine screenshots and text for better clarity. If it doesn’t fit, I can remove screens.

Comment (derekbruening) [reply drfuzz/drfuzz_mutator.c:208]: Use markdown for the literal text: I added it; bracket by triple backtic lines.

**Comment by Artem-OSSRevival** [comment]
Thanks for the corrections. I hope the next time it will turn out better.
