### PR TITLE
i#2522 strcasestr prototype error: Remove `const` from result type

### LINKED ISSUE #2522: BUILD: drmemory build failure caused by strcasestr declaration error
**Describe the bug**

strcasestr's definition is char *(const char *, const char *) whereas drmemory/common/utils.h uses the older
const char *(const char *, const char *).
This causes a build failure on linux (64-bit, recent vintage).
```
In file included from /tmp/drmemory/common/utils_shared.c:30:
/usr/include/string.h:380:14: error: conflicting types for ‘strcasestr’; have ‘char *(const char *, const char *)’
  380 | extern char *strcasestr (const char *__haystack, const char *__needle)
      |              ^~~~~~~~~~
In file included from /tmp/drmemory/common/utils_shared.c:28:
/tmp/drmemory/common/utils.h:1015:1: note: previous declaration of ‘strcasestr’ with type ‘\
const char *(const char *, const char *)’
 1015 | strcasestr(const char *text, const char *pattern);
      | ^~~~~~~~~~
```

**To Reproduce**

$ git clone https://github.com/DynamoRIO/drmemory.git
$ cd drmemory
$ ./make/git/dev-setup.sh
$ cd ..
$ mkdir build
$ cd build
$ cmake ../drmemory
$ make -k # other failures may be present: -k keeps going so that strcasestr failure is seen

**Versions**
 - What version of Dr. Memory are you using? git head @bfbc4a118a58a182770d306120cad41b9893c53

### PR DESCRIPTION
**Pull request by xdje42**
The definition of strcasestr is

char *strcasestr(const char *text, const char *pattern);

but drmemory uses

const char *strcasestr(const char *text, const char *pattern);

This causes build errors when both /usr/include/string.h and common/utils.h are included in linux. The definition for strcasestr for C has always not had the `const` in the result type (going back to its original addition to glibc in 1997). Thus we're pretty safe in not breaking anything on *nix. The other main use case of drmemory's strcasestr is on Windows, which does not have strcasestr.

Tested:
$ cmake && make
Also, there are failures in the clang and x86 workflows, but comparing the logs before/after
shows all failures pre-exist this patch, no new failures.

Here is the complete audit, all failures are pre-existing.

Recorded (errantly) as i#1938 failures:
  - wrap_operators: "internal crash" (Received SIGSEGV)
    - filed as #2535
  - wrap_cs2bug: CHECK_TRUNCATE_TYPE_sbyte(new_offs) (#2342)
  - pcache-use: "Usage error: meta-instr faulted? must set translation field and handle fault!" (#2202)
  - app_suite: vsyscall incorrect assumption (#2491)
  - app_suite.pattern: assert failure: save->ignore_next_delete == 0 (premature deletion)
    - filed as i#2537
  - fuzz_threads: vsyscall incorrect assumption (#2491)

Note: The above are marked as expected failures but [runsuite_wrapper.pl hardwires the addition of "i#1938" to test output](https://github.com/DynamoRIO/drmemory/blob/master/tests/runsuite_wrapper.pl#L281). #2534

Not currently recorded as expected failures (all #2491 - vsyscall incorrect assumption):
  - selfmod
  - syscalls_unix
  - clone
  - pthread_test
  - realloc

Fixes #2522

### CODE REVIEW

**Comment by derekbruening** [comment]
@xdje42 external users seem to be hitting this issue, would be good to get this merged: https://groups.google.com/g/dynamorio-users/c/WeQqxjwuPDI

File: common/utils.h [hunk 1]
```diff
@@ -1011,7 +1011,7 @@ drmem_strndup(const char *src, size_t max, heapstat_t type);
 #define MAX_OPTION_LEN DR_MAX_OPTIONS_LENGTH
```
Comment (derekbruening) [inline common/utils.h:1011]: > Also, there are failures in the clang and x86 workflows, but comparing the logs before/after
shows all failures pre-exist this patch, no new failures.

This is not sufficient: as with any test failure in any pull request, you need to cite a filed issue on the failure.  If there is no issue, file a new one.

You can see these are "vsyscall incorrect assumption" which is #2491 which was caused by Github switching to AMD hardware.  Please update the PR to include this.

If you have a chance, you can contribute to cleanup by adding these to the ignore list in a separate PR to get the tests green, so the next person doesn't have to deal with red tests.

**Review by derekbruening — APPROVED** [review]

File: common/utils.h (hunk 1 above)
Comment (xdje42) [reply common/utils.h:1011]: Have you seen the number of failures? How did it get so bad?
